package cli

import (
	"bytes"
	"context"
	"errors"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"sync"
	"testing"
)

// fakeDocker records what Houston asks docker to do.
type fakeDocker struct {
	lookErr    error
	versionErr error  // docker version
	composeErr error  // docker compose version
	psOut      string // what `docker ps` prints
	runExit    int
	runs       [][]string
	runDirs    []string
	runEnvs    [][]string
	runResult  func(args []string) (int, error) // optional; default is runExit, nil
	outputs    [][]string
	onRun      func() // called when Run is invoked, to inspect the filesystem
	// outputFn answers an Output call first, when it handles it.
	outputFn func(args []string) (out []byte, err error, handled bool)
	// streamFn answers a Stream call (default: exit 0 at once).
	streamFn func(ctx context.Context, args []string) (int, error)
	streams  [][]string
	mu       sync.Mutex // the route is registered while compose runs
}

func (f *fakeDocker) LookPath() error { return f.lookErr }

// devProxyVerbs are houston dev's calls around the proxy, the network and
// volumes: they succeed with no output unless outputFn says otherwise.
var devProxyVerbs = map[string]bool{"network": true, "inspect": true, "run": true, "start": true, "rm": true, "exec": true, "volume": true, "pause": true, "unpause": true}

func (f *fakeDocker) Output(args ...string) ([]byte, error) {
	f.mu.Lock()
	f.outputs = append(f.outputs, args)
	fn := f.outputFn
	f.mu.Unlock()
	if fn != nil {
		if out, err, handled := fn(args); handled {
			return out, err
		}
	}
	switch {
	case len(args) > 0 && args[0] == "version":
		return []byte("29.4.0\n"), f.versionErr
	case len(args) > 1 && args[0] == "compose" && args[1] == "version":
		return []byte("5.5.1\n"), f.composeErr
	case len(args) > 0 && args[0] == "ps":
		return []byte(f.psOut), nil
	case len(args) > 0 && devProxyVerbs[args[0]]:
		return nil, nil
	}
	return nil, errors.New("unexpected Output call")
}

func (f *fakeDocker) Run(dir string, env []string, args ...string) (int, error) {
	f.mu.Lock()
	f.runs = append(f.runs, args)
	f.runDirs = append(f.runDirs, dir)
	f.runEnvs = append(f.runEnvs, env)
	f.mu.Unlock()
	if f.onRun != nil {
		f.onRun()
	}
	if f.runResult != nil {
		return f.runResult(args)
	}
	return f.runExit, nil
}

func (f *fakeDocker) Stream(ctx context.Context, dir string, env []string, out io.Writer, args ...string) (int, error) {
	f.mu.Lock()
	f.streams = append(f.streams, args)
	fn := f.streamFn
	f.mu.Unlock()
	if fn != nil {
		return fn(ctx, args)
	}
	return 0, nil
}

// called reports whether an Output call had these args.
func (f *fakeDocker) called(args ...string) bool {
	f.mu.Lock()
	defer f.mu.Unlock()
	for _, o := range f.outputs {
		if reflect.DeepEqual(o, args) {
			return true
		}
	}
	return false
}

func (f *fakeDocker) calls() int { return len(f.outputs) + len(f.runs) }

const phoenix = `name: phoenixapp
services:
  app:
    build: .
    ports: ["4000:4000"]
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@${DB_HOST:-db}/phoenixapp
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      LOG_LEVEL: ${LOG_LEVEL:-info}
    depends_on: [db]
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
x-houston:
  health: /health
`

const wantOverride = "# Generated by houston. Do not edit.\nservices:\n  app:\n    build:\n      target: dev\n    ports: !reset []\n    networks:\n      default: {}\n      houston-dev:\n        aliases:\n          - phoenixapp.localhost\n  db:\n    ports: !reset []\nnetworks:\n  houston-dev:\n    external: true\n"

// newProject writes compose.yml (and optional extra files) into a temp dir and
// returns the dir and the compose file's absolute path.
func newProject(t *testing.T, compose string, files map[string]string) (string, string) {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "compose.yml")
	must(t, os.WriteFile(path, []byte(compose), 0o644))
	for name, content := range files {
		must(t, os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755))
		must(t, os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644))
	}
	return dir, path
}

func run(d *fakeDocker, args ...string) (code int, stdout, stderr string) {
	return runWithInput(d, "", args...)
}

func runWithInput(d *fakeDocker, input string, args ...string) (code int, stdout, stderr string) {
	var out, errOut bytes.Buffer
	code = Main(args, strings.NewReader(input), &out, &errOut, d)
	return code, out.String(), errOut.String()
}

func must(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatal(err)
	}
}

func upArgs(dir, path string) []string {
	return []string{"compose", "-p", "phoenixapp", "--project-directory", dir, "-f", path, "-f", filepath.Join(dir, ".houston", "compose.dev.yml"), "up", "--build"}
}

func TestDev_RunsComposeWithOverride(t *testing.T) {
	// A stray COMPOSE_PROJECT_NAME would rename the containers; -p pins the name.
	dir, path := newProject(t, phoenix, map[string]string{".env": "POSTGRES_PASSWORD=x\nSECRET_KEY_BASE=y\nCOMPOSE_PROJECT_NAME=other\n"})
	t.Setenv("COMPOSE_PROJECT_NAME", "other")
	var atRun string
	d := &fakeDocker{runExit: 3, onRun: func() {
		b, _ := os.ReadFile(filepath.Join(dir, ".houston", "compose.dev.yml"))
		atRun = string(b)
	}}

	code, _, stderr := run(d, "-f", path, "dev")

	if code != 3 {
		t.Errorf("exit = %d, want compose's 3 (stderr: %s)", code, stderr)
	}
	if len(d.runs) != 1 || !reflect.DeepEqual(d.runs[0], upArgs(dir, path)) {
		t.Fatalf("runs = %q\nwant %q", d.runs, upArgs(dir, path))
	}
	if d.runDirs[0] != dir {
		t.Errorf("run dir = %q, want %q", d.runDirs[0], dir)
	}
	if atRun != wantOverride {
		t.Errorf("override when compose ran =\n%s\nwant\n%s", atRun, wantOverride)
	}
	if stderr != "houston: phoenixapp is up at http://phoenixapp.localhost\n" {
		t.Errorf("unexpected stderr: %s", stderr)
	}
}

func TestDev_InvalidConfigExits2WithoutDocker(t *testing.T) {
	dir, path := newProject(t, strings.Replace(phoenix, "health: /health", "health: health", 1), nil)
	d := &fakeDocker{}

	code, _, stderr := run(d, "-f", path, "dev")

	if code != 2 {
		t.Errorf("exit = %d, want 2", code)
	}
	if !strings.Contains(stderr, "x-houston.health") {
		t.Errorf("stderr doesn't list the problem: %s", stderr)
	}
	if d.calls() != 0 {
		t.Errorf("docker was called: outputs %q runs %q", d.outputs, d.runs)
	}
	if _, err := os.Stat(filepath.Join(dir, ".houston")); !os.IsNotExist(err) {
		t.Errorf(".houston was created")
	}
}

func TestDev_DockerPreflight(t *testing.T) {
	boom := errors.New("boom")
	cases := []struct {
		name string
		d    *fakeDocker
		msg  string
	}{
		{"not installed", &fakeDocker{lookErr: boom}, "Docker isn't installed"},
		{"not running", &fakeDocker{versionErr: boom}, "Docker isn't running"},
		{"no compose v2", &fakeDocker{composeErr: boom}, "Docker Compose v2"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir, path := newProject(t, phoenix, nil)
			code, _, stderr := run(tc.d, "-f", path, "dev")
			if code != 1 {
				t.Errorf("exit = %d, want 1", code)
			}
			if !strings.Contains(stderr, tc.msg) {
				t.Errorf("stderr = %q, want %q", stderr, tc.msg)
			}
			if len(tc.d.runs) != 0 {
				t.Errorf("compose ran: %q", tc.d.runs)
			}
			if _, err := os.Stat(filepath.Join(dir, ".houston")); !os.IsNotExist(err) {
				t.Errorf(".houston was created")
			}
		})
	}
}

func TestDev_WarnsAboutVariables(t *testing.T) {
	cases := []struct {
		name    string
		env     *string // nil → no .env
		shell   map[string]string
		listed  []string
		missing bool // expects the ".env is missing" wording
	}{
		{"no .env", nil, nil, []string{"POSTGRES_PASSWORD", "SECRET_KEY_BASE"}, true},
		{"blank and absent", ptr("SECRET_KEY_BASE=\nOTHER=hunter2\n"), nil, []string{"POSTGRES_PASSWORD", "SECRET_KEY_BASE"}, false},
		{"set in the shell", ptr("SECRET_KEY_BASE=abc\n"), map[string]string{"POSTGRES_PASSWORD": "from-shell"}, nil, false},
		{"all set", ptr("POSTGRES_PASSWORD=p\nSECRET_KEY_BASE=hunter2\n"), nil, nil, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			for k, v := range tc.shell {
				t.Setenv(k, v)
			}
			files := map[string]string{}
			if tc.env != nil {
				files[".env"] = *tc.env
			}
			_, path := newProject(t, phoenix, files)
			d := &fakeDocker{}

			code, _, stderr := run(d, "-f", path, "dev")

			if code != 0 || len(d.runs) != 1 {
				t.Fatalf("exit = %d, runs = %d; warnings must not stop dev (stderr: %s)", code, len(d.runs), stderr)
			}
			for _, name := range tc.listed {
				if !strings.Contains(stderr, name) {
					t.Errorf("stderr doesn't list %s: %s", name, stderr)
				}
			}
			if tc.listed == nil && withoutUpLine(stderr) != "" {
				t.Errorf("unexpected warning: %s", stderr)
			}
			for _, never := range []string{"DB_HOST", "LOG_LEVEL", "hunter2", "from-shell"} {
				if strings.Contains(stderr, never) {
					t.Errorf("stderr mentions %q: %s", never, stderr)
				}
			}
			if tc.missing && !strings.Contains(stderr, "no .env") {
				t.Errorf("stderr doesn't say .env is missing: %s", stderr)
			}
		})
	}
}

func TestDev_BadDotEnvExits2(t *testing.T) {
	_, path := newProject(t, phoenix, map[string]string{".env": "POSTGRES_PASSWORD=\"unterminated\n"})
	d := &fakeDocker{}

	code, _, stderr := run(d, "-f", path, "dev")

	if code != 2 {
		t.Errorf("exit = %d, want 2", code)
	}
	if !strings.Contains(stderr, ".env") {
		t.Errorf("stderr doesn't name .env: %s", stderr)
	}
	if len(d.runs) != 0 {
		t.Errorf("compose ran: %q", d.runs)
	}
}

func TestDev_IgnoresOverrideFile(t *testing.T) {
	for _, name := range []string{"compose.override.yml", "compose.override.yaml"} {
		t.Run(name, func(t *testing.T) {
			dir, path := newProject(t, phoenix, map[string]string{
				".env": "POSTGRES_PASSWORD=x\nSECRET_KEY_BASE=y\n",
				name:   "services:\n  app:\n    privileged: true\n",
			})
			d := &fakeDocker{}

			code, _, stderr := run(d, "-f", path, "dev")

			if code != 0 {
				t.Fatalf("exit = %d (stderr: %s)", code, stderr)
			}
			if !strings.Contains(stderr, "ignores "+name) {
				t.Errorf("no warning about %s: %s", name, stderr)
			}
			if !reflect.DeepEqual(d.runs[0], upArgs(dir, path)) {
				t.Errorf("runs = %q, want %q", d.runs[0], upArgs(dir, path))
			}
		})
	}
}

func TestDev_GeneratedFile(t *testing.T) {
	env := map[string]string{".env": "POSTGRES_PASSWORD=x\nSECRET_KEY_BASE=y\n"}

	t.Run("replaces a stale file and reruns identically", func(t *testing.T) {
		files := map[string]string{".houston/compose.dev.yml": "stale\n"}
		for k, v := range env {
			files[k] = v
		}
		dir, path := newProject(t, phoenix, files)
		generated := filepath.Join(dir, ".houston", "compose.dev.yml")

		run(&fakeDocker{}, "-f", path, "dev")
		first, _ := os.ReadFile(generated)
		run(&fakeDocker{}, "-f", path, "dev")
		second, _ := os.ReadFile(generated)

		if string(first) != wantOverride || string(second) != wantOverride {
			t.Errorf("generated =\n%s\nthen\n%s\nwant\n%s", first, second, wantOverride)
		}
		var names []string
		entries, _ := os.ReadDir(filepath.Join(dir, ".houston"))
		for _, e := range entries {
			names = append(names, e.Name())
		}
		if !reflect.DeepEqual(names, []string{".gitignore", "compose.dev.yml"}) {
			t.Errorf(".houston holds %v, want .gitignore and compose.dev.yml (temp files left behind?)", names)
		}
		if ignore, _ := os.ReadFile(filepath.Join(dir, ".houston", ".gitignore")); string(ignore) != "*\n" {
			t.Errorf(".houston/.gitignore = %q, want \"*\\n\" so the folder is never committed", ignore)
		}
	})

	t.Run(".houston is a file", func(t *testing.T) {
		files := map[string]string{".houston": "not a dir\n"}
		for k, v := range env {
			files[k] = v
		}
		_, path := newProject(t, phoenix, files)
		d := &fakeDocker{}

		code, _, stderr := run(d, "-f", path, "dev")

		if code != 1 {
			t.Errorf("exit = %d, want 1", code)
		}
		if !strings.Contains(stderr, "can't write .houston/compose.dev.yml") {
			t.Errorf("stderr = %s", stderr)
		}
		if len(d.runs) != 0 {
			t.Errorf("compose ran: %q", d.runs)
		}
	})
}

func TestCLI_FileFlagAndUsageErrors(t *testing.T) {
	t.Run("relative -f", func(t *testing.T) {
		root := t.TempDir()
		sub := filepath.Join(root, "sub")
		must(t, os.MkdirAll(sub, 0o755))
		must(t, os.WriteFile(filepath.Join(sub, "compose.yml"), []byte(phoenix), 0o644))
		must(t, os.WriteFile(filepath.Join(sub, ".env"), []byte("POSTGRES_PASSWORD=x\nSECRET_KEY_BASE=y\n"), 0o644))
		t.Chdir(root)
		d := &fakeDocker{}

		code, _, stderr := run(d, "-f", "sub/compose.yml", "dev")

		if code != 0 {
			t.Fatalf("exit = %d (stderr: %s)", code, stderr)
		}
		wantDir, _ := filepath.EvalSymlinks(sub)
		gotDir, _ := filepath.EvalSymlinks(d.runDirs[0])
		if gotDir != wantDir {
			t.Errorf("project dir = %q, want %q", d.runDirs[0], sub)
		}
	})
	// Like docker compose: -f/--file goes before the command (houston -f x dev).
	t.Run("file flag after the command", func(t *testing.T) {
		_, path := newProject(t, phoenix, map[string]string{".env": "POSTGRES_PASSWORD=x\nSECRET_KEY_BASE=y\n"})
		for _, args := range [][]string{{"dev", "-f", path}, {"test", "--file", path}} {
			d := &fakeDocker{}
			code, _, stderr := run(d, args...)
			if code != 2 || d.calls() != 0 || !strings.Contains(stderr, "unknown") {
				t.Errorf("%q: exit = %d, calls = %d, stderr = %q; want a usage error", args, code, d.calls(), stderr)
			}
		}
	})
	for _, args := range [][]string{{"dev", "--server"}, {"dev", "--production"}, {"dev", "--nope"}, {"bogus"}} {
		t.Run(strings.Join(args, " "), func(t *testing.T) {
			d := &fakeDocker{}
			code, _, stderr := run(d, args...)
			if code != 2 {
				t.Errorf("exit = %d, want 2 (stderr: %s)", code, stderr)
			}
			if d.calls() != 0 {
				t.Errorf("docker was called")
			}
		})
	}
}

func ptr(s string) *string { return &s }

// withoutUpLine drops houston dev's "… is up at http://…" line, for tests
// about everything else it prints.
func withoutUpLine(stderr string) string {
	var kept []string
	for _, line := range strings.SplitAfter(stderr, "\n") {
		if !strings.Contains(line, " is up at http://") {
			kept = append(kept, line)
		}
	}
	return strings.Join(kept, "")
}
