// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board.sql

package models

import (
	"context"
	"database/sql"
)

const defaultStorage = `-- name: DefaultStorage :one
SELECT id, name, kind, settings, credentials, restic_password, is_default, acknowledged_at, verified_at, pruned_at, prune_error, created_at, updated_at FROM storage_locations WHERE is_default LIMIT 1
`

func (q *Queries) DefaultStorage(ctx context.Context) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, defaultStorage)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Settings,
		&i.Credentials,
		&i.ResticPassword,
		&i.IsDefault,
		&i.AcknowledgedAt,
		&i.VerifiedAt,
		&i.PrunedAt,
		&i.PruneError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletingProjects = `-- name: DeletingProjects :many
SELECT project_id FROM project_deletions WHERE project_id IS NOT NULL
  AND (status IN ('queued', 'running') OR (status = 'no_go' AND removing_at IS NOT NULL))
`

func (q *Queries) DeletingProjects(ctx context.Context) ([]sql.NullInt64, error) {
	rows, err := q.db.QueryContext(ctx, deletingProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullInt64{}
	for rows.Next() {
		var project_id sql.NullInt64
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failedBackupProjects = `-- name: FailedBackupProjects :many
SELECT project_id FROM backup_runs WHERE id IN (SELECT MAX(id) FROM backup_runs WHERE operation = 'backup' GROUP BY project_id) AND status = 'no_go'
`

// The projects whose latest backup is NO-GO.
func (q *Queries) FailedBackupProjects(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, failedBackupProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var project_id int64
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastGoBackups = `-- name: LastGoBackups :many
SELECT id, project_id, location_id, operation, kind, reason, status, deploy_number, scheduled_for, sha, snapshot_id, source_snapshot_id, bytes, found, error, log, token_digest, heartbeat_at, started_at, finished_at, created_at, updated_at FROM backup_runs WHERE id IN (SELECT MAX(id) FROM backup_runs WHERE operation = 'backup' AND status = 'go' GROUP BY project_id)
`

// Each project's last good backup.
func (q *Queries) LastGoBackups(ctx context.Context) ([]BackupRun, error) {
	rows, err := q.db.QueryContext(ctx, lastGoBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BackupRun{}
	for rows.Next() {
		var i BackupRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.LocationID,
			&i.Operation,
			&i.Kind,
			&i.Reason,
			&i.Status,
			&i.DeployNumber,
			&i.ScheduledFor,
			&i.Sha,
			&i.SnapshotID,
			&i.SourceSnapshotID,
			&i.Bytes,
			&i.Found,
			&i.Error,
			&i.Log,
			&i.TokenDigest,
			&i.HeartbeatAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shownUpdate = `-- name: ShownUpdate :one
SELECT id, to_version, from_version, status, step, log, started_at, finished_at, created_at, updated_at FROM server_updates WHERE status = 'running' OR finished_at >= ?1
ORDER BY status = 'running' DESC, finished_at DESC LIMIT 1
`

// What the board says of the server's update: the running one, or the last
// to finish since @since.
func (q *Queries) ShownUpdate(ctx context.Context, since sql.NullTime) (ServerUpdate, error) {
	row := q.db.QueryRowContext(ctx, shownUpdate, since)
	var i ServerUpdate
	err := row.Scan(
		&i.ID,
		&i.ToVersion,
		&i.FromVersion,
		&i.Status,
		&i.Step,
		&i.Log,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
