// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package models

import (
	"context"
	"time"
)

const addSetupCode = `-- name: AddSetupCode :exec
INSERT INTO setup_codes (code_digest) VALUES (?)
`

func (q *Queries) AddSetupCode(ctx context.Context, codeDigest string) error {
	_, err := q.db.ExecContext(ctx, addSetupCode, codeDigest)
	return err
}

const addUser = `-- name: AddUser :one
INSERT INTO users (email_address, password_digest, created_at, updated_at) VALUES (?, ?, ?, ?) RETURNING id
`

type AddUserParams struct {
	EmailAddress   string
	PasswordDigest string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.EmailAddress,
		arg.PasswordDigest,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const defaultStorageReady = `-- name: DefaultStorageReady :one
SELECT EXISTS (SELECT 1 FROM storage_locations WHERE is_default AND acknowledged_at IS NOT NULL) AS ready
`

func (q *Queries) DefaultStorageReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, defaultStorageReady)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}

const forgetSetupCodes = `-- name: ForgetSetupCodes :exec
DELETE FROM setup_codes
`

func (q *Queries) ForgetSetupCodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, forgetSetupCodes)
	return err
}

const liveRunners = `-- name: LiveRunners :one
SELECT count(*) FROM runners WHERE last_seen_at >= ?
`

// Runners heard from in the last minute.
func (q *Queries) LiveRunners(ctx context.Context, lastSeenAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, liveRunners, lastSeenAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setupCodes = `-- name: SetupCodes :many
SELECT id, code_digest FROM setup_codes
`

type SetupCodesRow struct {
	ID         int64
	CodeDigest string
}

func (q *Queries) SetupCodes(ctx context.Context) ([]SetupCodesRow, error) {
	rows, err := q.db.QueryContext(ctx, setupCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetupCodesRow{}
	for rows.Next() {
		var i SetupCodesRow
		if err := rows.Scan(&i.ID, &i.CodeDigest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useSetupCode = `-- name: UseSetupCode :execrows
DELETE FROM setup_codes WHERE id = ?
`

// Exactly one request can use a code: the one whose delete removes it.
func (q *Queries) UseSetupCode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, useSetupCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (SELECT 1 FROM users) AS present
`

func (q *Queries) UserExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists)
	var present bool
	err := row.Scan(&present)
	return present, err
}
