// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: volumes.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const ensureProjectVolume = `-- name: EnsureProjectVolume :exec
INSERT INTO project_volumes (project_id, name) VALUES (?, ?) ON CONFLICT (project_id, name) DO NOTHING
`

type EnsureProjectVolumeParams struct {
	ProjectID int64
	Name      string
}

// The unique (project, name) settles two syncs at once.
func (q *Queries) EnsureProjectVolume(ctx context.Context, arg EnsureProjectVolumeParams) error {
	_, err := q.db.ExecContext(ctx, ensureProjectVolume, arg.ProjectID, arg.Name)
	return err
}

const liveStorageLocations = `-- name: LiveStorageLocations :many
SELECT id, name, kind, settings, credentials, restic_password, is_default, acknowledged_at, verified_at, pruned_at, prune_error, created_at, updated_at FROM storage_locations WHERE kind IN ('nfs', 'local') ORDER BY id
`

// The locations that hold live volumes: an NFS export, a folder.
func (q *Queries) LiveStorageLocations(ctx context.Context) ([]StorageLocation, error) {
	rows, err := q.db.QueryContext(ctx, liveStorageLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLocation{}
	for rows.Next() {
		var i StorageLocation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Settings,
			&i.Credentials,
			&i.ResticPassword,
			&i.IsDefault,
			&i.AcknowledgedAt,
			&i.VerifiedAt,
			&i.PrunedAt,
			&i.PruneError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVolumePlaced = `-- name: MarkVolumePlaced :exec
UPDATE project_volumes SET placed_at = ?, updated_at = ? WHERE id = ? AND placed_at IS NULL
`

type MarkVolumePlacedParams struct {
	PlacedAt  sql.NullTime
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) MarkVolumePlaced(ctx context.Context, arg MarkVolumePlacedParams) error {
	_, err := q.db.ExecContext(ctx, markVolumePlaced, arg.PlacedAt, arg.UpdatedAt, arg.ID)
	return err
}

const projectVolumeByName = `-- name: ProjectVolumeByName :one
SELECT id, project_id, name, location_id, placed_at, created_at, updated_at FROM project_volumes WHERE project_id = ? AND name = ?
`

type ProjectVolumeByNameParams struct {
	ProjectID int64
	Name      string
}

func (q *Queries) ProjectVolumeByName(ctx context.Context, arg ProjectVolumeByNameParams) (ProjectVolume, error) {
	row := q.db.QueryRowContext(ctx, projectVolumeByName, arg.ProjectID, arg.Name)
	var i ProjectVolume
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.LocationID,
		&i.PlacedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const storageLocationByID = `-- name: StorageLocationByID :one
SELECT id, name, kind, settings, credentials, restic_password, is_default, acknowledged_at, verified_at, pruned_at, prune_error, created_at, updated_at FROM storage_locations WHERE id = ?
`

func (q *Queries) StorageLocationByID(ctx context.Context, id int64) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, storageLocationByID, id)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Settings,
		&i.Credentials,
		&i.ResticPassword,
		&i.IsDefault,
		&i.AcknowledgedAt,
		&i.VerifiedAt,
		&i.PrunedAt,
		&i.PruneError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
