// Package variant builds the per-place compose overrides Houston layers on top
// of a project's compose.yml.
package variant

import (
	"bytes"
	"sort"
	"strconv"

	"github.com/compose-spec/compose-go/v2/types"
	"github.com/scttymn/houston/internal/project"
	"go.yaml.in/yaml/v3"
)

const header = "# Generated by houston. Do not edit.\n"

// DevNetwork is the Docker network houston-dev-proxy reaches apps on.
const DevNetwork = "houston-dev"

// Route is how houston dev serves the app (docs/plans/dev-localhost.md): by
// name through houston-dev-proxy, which reaches it on DevNetwork as Alias;
// with no service publishing a host port. KeepPorts (--ports) leaves
// compose.yml's published ports as they are instead.
type Route struct {
	Alias     string
	KeepPorts bool
}

// DevOverride is the compose file Houston layers on top of compose.yml for
// `houston dev`: the app's dev build target, and the route.
func DevOverride(p *project.Project, r Route) []byte {
	app := []any{"build", mapping("target", scalar("dev"))}
	return render(routed(p, r, app))
}

// routed is the override with the app service's keys, plus the route: every
// service's published ports reset (unless kept), and the app on DevNetwork
// under its alias.
func routed(p *project.Project, r Route, app []any) *yaml.Node {
	if r.KeepPorts {
		return mapping("services", mapping(p.AppService, mapping(app...)))
	}
	var services []any
	for _, name := range sortedServices(p) {
		svc := []any{}
		if name == p.AppService {
			svc = append(append(svc, app...), "networks", mapping(
				"default", &yaml.Node{Kind: yaml.MappingNode, Style: yaml.FlowStyle},
				DevNetwork, mapping("aliases", &yaml.Node{Kind: yaml.SequenceNode, Content: []*yaml.Node{scalar(r.Alias)}}),
			))
			// build first, then ports, then the rest, as a reader expects
			svc = append(svc[:2], append([]any{"ports", tagged("!reset")}, svc[2:]...)...)
		} else {
			svc = append(svc, "ports", tagged("!reset"))
		}
		services = append(services, name, mapping(svc...))
	}
	return mapping(
		"services", mapping(services...),
		"networks", mapping(DevNetwork, mapping("external", scalar("true"))),
	)
}

// TestOverride is the compose file Houston layers on top of compose.yml for
// `houston test`: the test build target, no published ports anywhere, and
// only the app's named volumes (bind mounts are dev-only). It uses compose's
// !reset and !override tags to remove what the base file sets.
func TestOverride(p *project.Project) []byte {
	var services []any
	for _, name := range sortedServices(p) {
		svc := []any{}
		if name == p.AppService {
			svc = append(svc, "build", mapping("target", scalar("test")))
		}
		svc = append(svc, "ports", tagged("!reset"))
		if name == p.AppService {
			if volumes := p.Compose.Services[name].Volumes; len(volumes) > 0 {
				svc = append(svc, "volumes", namedVolumes(volumes))
			}
		}
		services = append(services, name, mapping(svc...))
	}
	return render(mapping("services", mapping(services...)))
}

func sortedServices(p *project.Project) []string {
	names := make([]string, 0, len(p.Compose.Services))
	for name := range p.Compose.Services {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// namedVolumes replaces the app's volume list with only its named volumes,
// or resets it when there are none.
func namedVolumes(volumes []types.ServiceVolumeConfig) *yaml.Node {
	var named []*yaml.Node
	for _, v := range volumes {
		if v.Type != types.VolumeTypeVolume {
			continue
		}
		spec := v.Source + ":" + v.Target
		if v.ReadOnly {
			spec += ":ro"
		}
		named = append(named, scalar(spec))
	}
	if len(named) == 0 {
		return tagged("!reset")
	}
	return &yaml.Node{Kind: yaml.SequenceNode, Tag: "!override", Content: named}
}

// mapping builds a YAML mapping from alternating keys (strings) and values
// (nodes), keeping their order.
func mapping(pairs ...any) *yaml.Node {
	n := &yaml.Node{Kind: yaml.MappingNode}
	for i := 0; i < len(pairs); i += 2 {
		n.Content = append(n.Content, scalar(pairs[i].(string)), pairs[i+1].(*yaml.Node))
	}
	return n
}

func scalar(s string) *yaml.Node { return &yaml.Node{Kind: yaml.ScalarNode, Value: s} }

// tagged is an empty flow sequence with a compose merge tag, e.g. `!reset []`.
func tagged(tag string) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Tag: tag, Style: yaml.FlowStyle}
}

func render(doc *yaml.Node) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		panic(err) // nodes built above always encode
	}
	return b.Bytes()
}

// ProductionOverride is the compose file Houston layers on top of compose.yml
// for `houston dev --production`: the production build target, no bind mounts
// (the code is baked into the image), and the app's published host port
// pointed at the port the production image listens on (x-houston.app_port).
func ProductionOverride(p *project.Project, r Route) []byte {
	app := p.Compose.Services[p.AppService]
	svc := []any{"build", mapping("target", scalar("production"))}
	if r.KeepPorts {
		port := strconv.Itoa(p.AppPort)
		if len(app.Ports) > 0 && app.Ports[0].Published != "" {
			port = app.Ports[0].Published + ":" + port
			if ip := app.Ports[0].HostIP; ip != "" {
				port = ip + ":" + port // keep a localhost-only binding localhost-only
			}
		}
		svc = append(svc, "ports", &yaml.Node{Kind: yaml.SequenceNode, Tag: "!override", Content: []*yaml.Node{quoted(port)}})
	}
	if len(app.Volumes) > 0 {
		svc = append(svc, "volumes", namedVolumes(app.Volumes))
	}
	return render(routed(p, r, svc))
}

// quoted keeps "3000:80" a string for every YAML reader (YAML 1.1 would read
// it as a base-60 number).
func quoted(s string) *yaml.Node {
	return &yaml.Node{Kind: yaml.ScalarNode, Value: s, Style: yaml.DoubleQuotedStyle}
}
