// Package variant builds the per-place compose overrides Houston layers on top
// of a project's compose.yml.
package variant

import (
	"bytes"
	"sort"

	"github.com/compose-spec/compose-go/v2/types"
	"github.com/sevenmoons/houston/internal/project"
	"go.yaml.in/yaml/v3"
)

const header = "# Generated by houston. Do not edit.\n"

// DevOverride is the compose file Houston layers on top of compose.yml for
// `houston dev`: it only forces the app's build target to dev. Everything
// else runs as written.
func DevOverride(p *project.Project) []byte {
	return render(mapping(
		"services", mapping(
			p.AppService, mapping(
				"build", mapping("target", scalar("dev")),
			),
		),
	))
}

// TestOverride is the compose file Houston layers on top of compose.yml for
// `houston test`: the test build target, no published ports anywhere, and
// only the app's named volumes (bind mounts are dev-only). It uses compose's
// !reset and !override tags to remove what the base file sets.
func TestOverride(p *project.Project) []byte {
	var services []any
	for _, name := range sortedServices(p) {
		svc := []any{}
		if name == p.AppService {
			svc = append(svc, "build", mapping("target", scalar("test")))
		}
		svc = append(svc, "ports", tagged("!reset"))
		if name == p.AppService {
			if volumes := p.Compose.Services[name].Volumes; len(volumes) > 0 {
				svc = append(svc, "volumes", namedVolumes(volumes))
			}
		}
		services = append(services, name, mapping(svc...))
	}
	return render(mapping("services", mapping(services...)))
}

func sortedServices(p *project.Project) []string {
	names := make([]string, 0, len(p.Compose.Services))
	for name := range p.Compose.Services {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// namedVolumes replaces the app's volume list with only its named volumes,
// or resets it when there are none.
func namedVolumes(volumes []types.ServiceVolumeConfig) *yaml.Node {
	var named []*yaml.Node
	for _, v := range volumes {
		if v.Type != types.VolumeTypeVolume {
			continue
		}
		spec := v.Source + ":" + v.Target
		if v.ReadOnly {
			spec += ":ro"
		}
		named = append(named, scalar(spec))
	}
	if len(named) == 0 {
		return tagged("!reset")
	}
	return &yaml.Node{Kind: yaml.SequenceNode, Tag: "!override", Content: named}
}

// mapping builds a YAML mapping from alternating keys (strings) and values
// (nodes), keeping their order.
func mapping(pairs ...any) *yaml.Node {
	n := &yaml.Node{Kind: yaml.MappingNode}
	for i := 0; i < len(pairs); i += 2 {
		n.Content = append(n.Content, scalar(pairs[i].(string)), pairs[i+1].(*yaml.Node))
	}
	return n
}

func scalar(s string) *yaml.Node { return &yaml.Node{Kind: yaml.ScalarNode, Value: s} }

// tagged is an empty flow sequence with a compose merge tag, e.g. `!reset []`.
func tagged(tag string) *yaml.Node {
	return &yaml.Node{Kind: yaml.SequenceNode, Tag: tag, Style: yaml.FlowStyle}
}

func render(doc *yaml.Node) []byte {
	var b bytes.Buffer
	b.WriteString(header)
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		panic(err) // nodes built above always encode
	}
	return b.Bytes()
}
