package variant

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/sevenmoons/houston/internal/project"
)

func TestProductionOverride(t *testing.T) {
	header := "# Generated by houston. Do not edit.\nservices:\n"
	cases := []struct {
		name    string
		compose string // "" → the PhoenixApp fixture
		want    string
	}{
		{"phoenix", "", header +
			"  app:\n" +
			"    build:\n" +
			"      target: production\n" +
			"    ports: !override\n" +
			"      - \"4000:4000\"\n" +
			"    volumes: !override\n" +
			"      - media:/media\n"},
		{"rails on port 80", "name: demo\nservices:\n  app:\n    build: .\n    ports: [\"3000:3000\"]\n    volumes: [\".:/rails\", \"storage:/rails/storage\"]\nvolumes:\n  storage:\nx-houston:\n  health: /up\n  app_port: 80\n", header +
			"  app:\n" +
			"    build:\n" +
			"      target: production\n" +
			"    ports: !override\n" +
			"      - \"3000:80\"\n" +
			"    volumes: !override\n" +
			"      - storage:/rails/storage\n"},
		{"host IP is kept", "name: demo\nservices:\n  app:\n    build: .\n    ports: [\"127.0.0.1:3000:3000\"]\nx-houston:\n  health: /up\n  app_port: 80\n", header +
			"  app:\n" +
			"    build:\n" +
			"      target: production\n" +
			"    ports: !override\n" +
			"      - \"127.0.0.1:3000:80\"\n"},
		{"container-only port, no volumes", "name: demo\nservices:\n  web:\n    build: .\n    ports: [\"8080\"]\nx-houston:\n  health: /up\n", header +
			"  web:\n" +
			"    build:\n" +
			"      target: production\n" +
			"    ports: !override\n" +
			"      - \"8080\"\n"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			path := "../project/testdata/phoenixapp.compose.yml"
			if tc.compose != "" {
				path = filepath.Join(t.TempDir(), "compose.yml")
				if err := os.WriteFile(path, []byte(tc.compose), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			p, err := project.Load(path)
			if err != nil {
				t.Fatal(err)
			}
			if got := string(ProductionOverride(p)); got != tc.want {
				t.Errorf("ProductionOverride =\n%s\nwant\n%s", got, tc.want)
			}
		})
	}
}
