package variant

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/scttymn/houston/internal/project"
)

func TestTestOverride_Phoenix(t *testing.T) {
	p, err := project.Load("../project/testdata/phoenixapp.compose.yml")
	if err != nil {
		t.Fatal(err)
	}
	want := "# Generated by houston. Do not edit.\n" +
		"services:\n" +
		"  app:\n" +
		"    build:\n" +
		"      target: test\n" +
		"    ports: !reset []\n" +
		"    volumes: !override\n" +
		"      - media:/media\n" +
		"  cache:\n" +
		"    ports: !reset []\n" +
		"  db:\n" +
		"    ports: !reset []\n"
	first := string(TestOverride(p))
	if first != want {
		t.Errorf("TestOverride =\n%s\nwant\n%s", first, want)
	}
	if second := string(TestOverride(p)); second != first {
		t.Errorf("second call differs:\n%s", second)
	}
}

func TestTestOverride_NoNamedVolumes(t *testing.T) {
	path := filepath.Join(t.TempDir(), "compose.yml")
	compose := "name: demo\nservices:\n  web:\n    build: .\n    ports: [\"3000:3000\"]\n    volumes: [\".:/app\", \"./tmp:/tmp/x:ro\"]\nx-houston:\n  health: /up\n"
	if err := os.WriteFile(path, []byte(compose), 0o644); err != nil {
		t.Fatal(err)
	}
	p, err := project.Load(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# Generated by houston. Do not edit.\n" +
		"services:\n" +
		"  web:\n" +
		"    build:\n" +
		"      target: test\n" +
		"    ports: !reset []\n" +
		"    volumes: !reset []\n"
	if got := string(TestOverride(p)); got != want {
		t.Errorf("TestOverride =\n%s\nwant\n%s", got, want)
	}
}
