// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backup_runs.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const backupLocationFor = `-- name: BackupLocationFor :one
SELECT location.id, location.name, location.kind, location.settings, location.credentials, location.restic_password, location.is_default, location.acknowledged_at, location.verified_at, location.pruned_at, location.prune_error, location.created_at, location.updated_at FROM storage_locations location
WHERE location.acknowledged_at IS NOT NULL AND (location.id = ?1 OR (location.is_default AND NOT EXISTS (
  SELECT 1 FROM storage_locations chosen WHERE chosen.id = ?1 AND chosen.acknowledged_at IS NOT NULL)))
ORDER BY location.id LIMIT 1
`

// Where a project's backups go: its own location once set up, else the
// default (once setup's storage step is finished).
func (q *Queries) BackupLocationFor(ctx context.Context, chosen int64) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, backupLocationFor, chosen)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Settings,
		&i.Credentials,
		&i.ResticPassword,
		&i.IsDefault,
		&i.AcknowledgedAt,
		&i.VerifiedAt,
		&i.PrunedAt,
		&i.PruneError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBackupRun = `-- name: CreateBackupRun :one
INSERT INTO backup_runs (project_id, location_id, operation, kind, reason, deploy_number, source_snapshot_id, heartbeat_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, project_id, location_id, operation, kind, reason, status, deploy_number, scheduled_for, sha, snapshot_id, source_snapshot_id, bytes, found, error, log, token_digest, heartbeat_at, started_at, finished_at, created_at, updated_at
`

type CreateBackupRunParams struct {
	ProjectID        int64
	LocationID       int64
	Operation        string
	Kind             string
	Reason           string
	DeployNumber     sql.NullInt64
	SourceSnapshotID string
	HeartbeatAt      time.Time
}

func (q *Queries) CreateBackupRun(ctx context.Context, arg CreateBackupRunParams) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, createBackupRun,
		arg.ProjectID,
		arg.LocationID,
		arg.Operation,
		arg.Kind,
		arg.Reason,
		arg.DeployNumber,
		arg.SourceSnapshotID,
		arg.HeartbeatAt,
	)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.LocationID,
		&i.Operation,
		&i.Kind,
		&i.Reason,
		&i.Status,
		&i.DeployNumber,
		&i.ScheduledFor,
		&i.Sha,
		&i.SnapshotID,
		&i.SourceSnapshotID,
		&i.Bytes,
		&i.Found,
		&i.Error,
		&i.Log,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploySnapshot = `-- name: DeploySnapshot :one

SELECT id, project_id, location_id, operation, kind, reason, status, deploy_number, scheduled_for, sha, snapshot_id, source_snapshot_id, bytes, found, error, log, token_digest, heartbeat_at, started_at, finished_at, created_at, updated_at FROM backup_runs WHERE project_id = ? AND operation = 'backup' AND reason = ? AND deploy_number = ?
`

type DeploySnapshotParams struct {
	ProjectID    int64
	Reason       string
	DeployNumber sql.NullInt64
}

// the chosen one, or else the defaults: never both
func (q *Queries) DeploySnapshot(ctx context.Context, arg DeploySnapshotParams) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, deploySnapshot, arg.ProjectID, arg.Reason, arg.DeployNumber)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.LocationID,
		&i.Operation,
		&i.Kind,
		&i.Reason,
		&i.Status,
		&i.DeployNumber,
		&i.ScheduledFor,
		&i.Sha,
		&i.SnapshotID,
		&i.SourceSnapshotID,
		&i.Bytes,
		&i.Found,
		&i.Error,
		&i.Log,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreRun = `-- name: RestoreRun :one
SELECT id, project_id, location_id, operation, kind, reason, status, deploy_number, scheduled_for, sha, snapshot_id, source_snapshot_id, bytes, found, error, log, token_digest, heartbeat_at, started_at, finished_at, created_at, updated_at FROM backup_runs WHERE project_id = ? AND operation = 'restore' AND deploy_number = ?
`

type RestoreRunParams struct {
	ProjectID    int64
	DeployNumber sql.NullInt64
}

func (q *Queries) RestoreRun(ctx context.Context, arg RestoreRunParams) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, restoreRun, arg.ProjectID, arg.DeployNumber)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.LocationID,
		&i.Operation,
		&i.Kind,
		&i.Reason,
		&i.Status,
		&i.DeployNumber,
		&i.ScheduledFor,
		&i.Sha,
		&i.SnapshotID,
		&i.SourceSnapshotID,
		&i.Bytes,
		&i.Found,
		&i.Error,
		&i.Log,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
