// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deploys.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const abandonDeploy = `-- name: AbandonDeploy :exec
UPDATE deploys SET status = 'no_go', finished_at = ?1, error = ?2, updated_at = ?1 WHERE id = ?3
`

type AbandonDeployParams struct {
	Now   sql.NullTime
	Error string
	ID    int64
}

func (q *Queries) AbandonDeploy(ctx context.Context, arg AbandonDeployParams) error {
	_, err := q.db.ExecContext(ctx, abandonDeploy, arg.Now, arg.Error, arg.ID)
	return err
}

const appendLog = `-- name: AppendLog :exec
UPDATE deploys SET log = log || ? WHERE id = ?
`

type AppendLogParams struct {
	Log string
	ID  int64
}

func (q *Queries) AppendLog(ctx context.Context, arg AppendLogParams) error {
	_, err := q.db.ExecContext(ctx, appendLog, arg.Log, arg.ID)
	return err
}

const busyDeploy = `-- name: BusyDeploy :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE project_id = ? AND status IN ('queued', 'in_flight') ORDER BY number LIMIT 1
`

func (q *Queries) BusyDeploy(ctx context.Context, projectID int64) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, busyDeploy, projectID)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimQueued = `-- name: ClaimQueued :execrows
UPDATE deploys SET status = 'in_flight', runner = ?1, token_digest = ?2, generation = ?3,
  heartbeat_at = ?4, updated_at = ?4
WHERE id = ?5 AND status = 'queued'
`

type ClaimQueuedParams struct {
	Runner      string
	TokenDigest string
	Generation  int64
	Now         time.Time
	ID          int64
}

// Only if it's still queued: another runner may have had it since.
func (q *Queries) ClaimQueued(ctx context.Context, arg ClaimQueuedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimQueued,
		arg.Runner,
		arg.TokenDigest,
		arg.Generation,
		arg.Now,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createDeploy = `-- name: CreateDeploy :one
INSERT INTO deploys (project_id, number, kind, status, sha, ref, generation, token_digest, heartbeat_at, sync_payload)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at
`

type CreateDeployParams struct {
	ProjectID   int64
	Number      int64
	Kind        string
	Status      string
	Sha         string
	Ref         string
	Generation  int64
	TokenDigest string
	HeartbeatAt time.Time
	SyncPayload sql.NullString
}

func (q *Queries) CreateDeploy(ctx context.Context, arg CreateDeployParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, createDeploy,
		arg.ProjectID,
		arg.Number,
		arg.Kind,
		arg.Status,
		arg.Sha,
		arg.Ref,
		arg.Generation,
		arg.TokenDigest,
		arg.HeartbeatAt,
		arg.SyncPayload,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRestore = `-- name: CreateRestore :one
INSERT INTO deploys (project_id, number, kind, status, sha, ref, generation, heartbeat_at, source_snapshot_id, source_location_id)
VALUES (?, ?, 'restore', 'queued', ?, ?, ?, ?, ?, ?) RETURNING id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at
`

type CreateRestoreParams struct {
	ProjectID        int64
	Number           int64
	Sha              string
	Ref              string
	Generation       int64
	HeartbeatAt      time.Time
	SourceSnapshotID string
	SourceLocationID sql.NullInt64
}

func (q *Queries) CreateRestore(ctx context.Context, arg CreateRestoreParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, createRestore,
		arg.ProjectID,
		arg.Number,
		arg.Sha,
		arg.Ref,
		arg.Generation,
		arg.HeartbeatAt,
		arg.SourceSnapshotID,
		arg.SourceLocationID,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deployByID = `-- name: DeployByID :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE id = ?
`

func (q *Queries) DeployByID(ctx context.Context, id int64) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, deployByID, id)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deployByNumber = `-- name: DeployByNumber :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE project_id = ? AND number = ?
`

type DeployByNumberParams struct {
	ProjectID int64
	Number    int64
}

func (q *Queries) DeployByNumber(ctx context.Context, arg DeployByNumberParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, deployByNumber, arg.ProjectID, arg.Number)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deployInFlight = `-- name: DeployInFlight :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE project_id = ? AND status = 'in_flight'
`

func (q *Queries) DeployInFlight(ctx context.Context, projectID int64) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, deployInFlight, projectID)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deploySummaries = `-- name: DeploySummaries :many

SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, CAST('' AS TEXT) AS log, runner, proposed_name,
  token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at
FROM deploys WHERE project_id = ? ORDER BY number DESC LIMIT ? OFFSET ?
`

type DeploySummariesParams struct {
	ProjectID int64
	Limit     int64
	Offset    int64
}

type DeploySummariesRow struct {
	ID               int64
	ProjectID        int64
	Number           int64
	Kind             string
	Status           string
	Sha              string
	Ref              string
	Fresh            bool
	Generation       int64
	Step             string
	Error            string
	Log              string
	Runner           string
	ProposedName     string
	TokenDigest      string
	HeartbeatAt      time.Time
	FinishedAt       sql.NullTime
	SwitchedAt       sql.NullTime
	SourceLocationID sql.NullInt64
	SourceSnapshotID string
	SyncPayload      sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// A deploy without its log (up to 4 MiB): for lists. The columns are the
// table's, in order, so each row converts to a Deploy.
func (q *Queries) DeploySummaries(ctx context.Context, arg DeploySummariesParams) ([]DeploySummariesRow, error) {
	rows, err := q.db.QueryContext(ctx, deploySummaries, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeploySummariesRow{}
	for rows.Next() {
		var i DeploySummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Kind,
			&i.Status,
			&i.Sha,
			&i.Ref,
			&i.Fresh,
			&i.Generation,
			&i.Step,
			&i.Error,
			&i.Log,
			&i.Runner,
			&i.ProposedName,
			&i.TokenDigest,
			&i.HeartbeatAt,
			&i.FinishedAt,
			&i.SwitchedAt,
			&i.SourceLocationID,
			&i.SourceSnapshotID,
			&i.SyncPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const firstGo = `-- name: FirstGo :one
SELECT NOT EXISTS (SELECT 1 FROM deploys WHERE project_id = ? AND id != ? AND (status = 'go' OR switched_at IS NOT NULL)) AS is_first
`

type FirstGoParams struct {
	ProjectID int64
	ID        int64
}

// Whether nothing else of the project's has served: no other GO, no other
// switched restore.
func (q *Queries) FirstGo(ctx context.Context, arg FirstGoParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, firstGo, arg.ProjectID, arg.ID)
	var is_first bool
	err := row.Scan(&is_first)
	return is_first, err
}

const keepRestoreSync = `-- name: KeepRestoreSync :execrows
UPDATE deploys SET sync_payload = ? WHERE id = ? AND status = 'in_flight'
`

type KeepRestoreSyncParams struct {
	SyncPayload sql.NullString
	ID          int64
}

// A restore's check sync, kept while it's in flight, applied at its switch.
func (q *Queries) KeepRestoreSync(ctx context.Context, arg KeepRestoreSyncParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, keepRestoreSync, arg.SyncPayload, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const latestDeployByNumber = `-- name: LatestDeployByNumber :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE project_id = ? ORDER BY number DESC LIMIT 1
`

func (q *Queries) LatestDeployByNumber(ctx context.Context, projectID int64) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, latestDeployByNumber, projectID)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logSize = `-- name: LogSize :one
SELECT CAST(length(CAST(log AS BLOB)) AS INTEGER) AS log_size FROM deploys WHERE id = ?
`

// In bytes, without reading a log that can be megabytes.
func (q *Queries) LogSize(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, logSize, id)
	var log_size int64
	err := row.Scan(&log_size)
	return log_size, err
}

const markSwitched = `-- name: MarkSwitched :exec
UPDATE deploys SET switched_at = ? WHERE id = ? AND switched_at IS NULL
`

type MarkSwitchedParams struct {
	SwitchedAt sql.NullTime
	ID         int64
}

func (q *Queries) MarkSwitched(ctx context.Context, arg MarkSwitchedParams) error {
	_, err := q.db.ExecContext(ctx, markSwitched, arg.SwitchedAt, arg.ID)
	return err
}

const nextDeployNumber = `-- name: NextDeployNumber :one
SELECT CAST(COALESCE(MAX(number), 0) + 1 AS INTEGER) AS next FROM deploys WHERE project_id = ?
`

func (q *Queries) NextDeployNumber(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextDeployNumber, projectID)
	var next int64
	err := row.Scan(&next)
	return next, err
}

const nextQueued = `-- name: NextQueued :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE status = 'queued'
  AND project_id NOT IN (SELECT project_id FROM deploys WHERE status = 'in_flight')
ORDER BY created_at, id LIMIT 1
`

// The oldest queued deploy whose project has none in flight.
func (q *Queries) NextQueued(ctx context.Context) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, nextQueued)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectHasServed = `-- name: ProjectHasServed :one
SELECT EXISTS (SELECT 1 FROM deploys WHERE project_id = ? AND (status = 'go' OR switched_at IS NOT NULL)) AS served
`

// Whether anything it deployed or restored has served: a GO, or a switch.
func (q *Queries) ProjectHasServed(ctx context.Context, projectID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectHasServed, projectID)
	var served bool
	err := row.Scan(&served)
	return served, err
}

const queuedDeploy = `-- name: QueuedDeploy :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE project_id = ? AND status = 'queued'
`

func (q *Queries) QueuedDeploy(ctx context.Context, projectID int64) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, queuedDeploy, projectID)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueDeploy = `-- name: RequeueDeploy :one
UPDATE deploys SET sha = ?, ref = ?, fresh = ?, log = ?, updated_at = ? WHERE id = ? RETURNING id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at
`

type RequeueDeployParams struct {
	Sha       string
	Ref       string
	Fresh     bool
	Log       string
	UpdatedAt time.Time
	ID        int64
}

func (q *Queries) RequeueDeploy(ctx context.Context, arg RequeueDeployParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, requeueDeploy,
		arg.Sha,
		arg.Ref,
		arg.Fresh,
		arg.Log,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreHolding = `-- name: RestoreHolding :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE project_id = ?1 AND kind = 'restore'
  AND (status = 'queued' OR (status = 'in_flight' AND heartbeat_at >= ?2)) ORDER BY id LIMIT 1
`

type RestoreHoldingParams struct {
	ProjectID int64
	Since     time.Time
}

// A restore that owns its project's config: queued, or in flight and heard
// from since @since.
func (q *Queries) RestoreHolding(ctx context.Context, arg RestoreHoldingParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, restoreHolding, arg.ProjectID, arg.Since)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const restoreOrCopyUnderway = `-- name: RestoreOrCopyUnderway :one
SELECT EXISTS (SELECT 1 FROM deploys WHERE project_id = ? AND kind IN ('restore', 'copy') AND status IN ('queued', 'in_flight')) AS underway
`

// A restore or a copy queued or in flight owns what's deployed next.
func (q *Queries) RestoreOrCopyUnderway(ctx context.Context, projectID int64) (bool, error) {
	row := q.db.QueryRowContext(ctx, restoreOrCopyUnderway, projectID)
	var underway bool
	err := row.Scan(&underway)
	return underway, err
}

const restoreServing = `-- name: RestoreServing :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE project_id = ? AND kind = 'restore' AND generation = ? AND sha = ?
ORDER BY sync_payload IS NULL, number DESC LIMIT 1
`

type RestoreServingParams struct {
	ProjectID  int64
	Generation int64
	Sha        string
}

// The restore that built what kamal-proxy serves: of two of one commit, the
// one whose compose.yml was kept, then the newer.
func (q *Queries) RestoreServing(ctx context.Context, arg RestoreServingParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, restoreServing, arg.ProjectID, arg.Generation, arg.Sha)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runningDeploySummary = `-- name: RunningDeploySummary :one
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, CAST('' AS TEXT) AS log, runner, proposed_name,
  token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at
FROM deploys WHERE project_id = ? AND (status = 'go' OR switched_at IS NOT NULL) ORDER BY number DESC LIMIT 1
`

type RunningDeploySummaryRow struct {
	ID               int64
	ProjectID        int64
	Number           int64
	Kind             string
	Status           string
	Sha              string
	Ref              string
	Fresh            bool
	Generation       int64
	Step             string
	Error            string
	Log              string
	Runner           string
	ProposedName     string
	TokenDigest      string
	HeartbeatAt      time.Time
	FinishedAt       sql.NullTime
	SwitchedAt       sql.NullTime
	SourceLocationID sql.NullInt64
	SourceSnapshotID string
	SyncPayload      sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

// The latest GO, or a restore that switched without getting to GO,
// whichever is newer.
func (q *Queries) RunningDeploySummary(ctx context.Context, projectID int64) (RunningDeploySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, runningDeploySummary, projectID)
	var i RunningDeploySummaryRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveProgress = `-- name: SaveProgress :one
UPDATE deploys SET step = ?, error = ?, proposed_name = ?, status = ?, finished_at = ?, heartbeat_at = ?, updated_at = ?
WHERE id = ? RETURNING id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at
`

type SaveProgressParams struct {
	Step         string
	Error        string
	ProposedName string
	Status       string
	FinishedAt   sql.NullTime
	HeartbeatAt  time.Time
	UpdatedAt    time.Time
	ID           int64
}

func (q *Queries) SaveProgress(ctx context.Context, arg SaveProgressParams) (Deploy, error) {
	row := q.db.QueryRowContext(ctx, saveProgress,
		arg.Step,
		arg.Error,
		arg.ProposedName,
		arg.Status,
		arg.FinishedAt,
		arg.HeartbeatAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Deploy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Kind,
		&i.Status,
		&i.Sha,
		&i.Ref,
		&i.Fresh,
		&i.Generation,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.Runner,
		&i.ProposedName,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.FinishedAt,
		&i.SwitchedAt,
		&i.SourceLocationID,
		&i.SourceSnapshotID,
		&i.SyncPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const seeRunner = `-- name: SeeRunner :exec
INSERT INTO runners (name, last_seen_at, updated_at) VALUES (?1, ?2, ?2)
ON CONFLICT (name) DO UPDATE SET last_seen_at = excluded.last_seen_at, updated_at = excluded.updated_at
`

type SeeRunnerParams struct {
	Name string
	Now  time.Time
}

func (q *Queries) SeeRunner(ctx context.Context, arg SeeRunnerParams) error {
	_, err := q.db.ExecContext(ctx, seeRunner, arg.Name, arg.Now)
	return err
}

const staleInFlight = `-- name: StaleInFlight :many
SELECT id, project_id, number, kind, status, sha, ref, fresh, generation, step, error, log, runner, proposed_name, token_digest, heartbeat_at, finished_at, switched_at, source_location_id, source_snapshot_id, sync_payload, created_at, updated_at FROM deploys WHERE status = 'in_flight' AND heartbeat_at < ? ORDER BY id
`

func (q *Queries) StaleInFlight(ctx context.Context, heartbeatAt time.Time) ([]Deploy, error) {
	rows, err := q.db.QueryContext(ctx, staleInFlight, heartbeatAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deploy{}
	for rows.Next() {
		var i Deploy
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Kind,
			&i.Status,
			&i.Sha,
			&i.Ref,
			&i.Fresh,
			&i.Generation,
			&i.Step,
			&i.Error,
			&i.Log,
			&i.Runner,
			&i.ProposedName,
			&i.TokenDigest,
			&i.HeartbeatAt,
			&i.FinishedAt,
			&i.SwitchedAt,
			&i.SourceLocationID,
			&i.SourceSnapshotID,
			&i.SyncPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
