// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installations.sql

package models

import (
	"context"
)

const installationBaseDomain = `-- name: InstallationBaseDomain :one
SELECT base_domain FROM installations WHERE id = 1
`

// The base domain setup chose ("" before it did); no row before setup.
func (q *Queries) InstallationBaseDomain(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, installationBaseDomain)
	var base_domain string
	err := row.Scan(&base_domain)
	return base_domain, err
}
