// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_page.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const copyCameFrom = `-- name: CopyCameFrom :one
SELECT id, project_id, from_project_id, deploy_id, snapshot_run_id, from_name, to_name, sha, requested_by, status, error, log, handed_over, handed_over_at, undone_at, created_at, updated_at FROM project_copies WHERE project_id = ? AND status = 'go' AND undone_at IS NULL AND from_project_id IS NOT NULL ORDER BY id DESC LIMIT 1
`

// The copy that made a project, while its old project's there.
func (q *Queries) CopyCameFrom(ctx context.Context, projectID sql.NullInt64) (ProjectCopy, error) {
	row := q.db.QueryRowContext(ctx, copyCameFrom, projectID)
	var i ProjectCopy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromProjectID,
		&i.DeployID,
		&i.SnapshotRunID,
		&i.FromName,
		&i.ToName,
		&i.Sha,
		&i.RequestedBy,
		&i.Status,
		&i.Error,
		&i.Log,
		&i.HandedOver,
		&i.HandedOverAt,
		&i.UndoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const copyWentTo = `-- name: CopyWentTo :one
SELECT id, project_id, from_project_id, deploy_id, snapshot_run_id, from_name, to_name, sha, requested_by, status, error, log, handed_over, handed_over_at, undone_at, created_at, updated_at FROM project_copies WHERE from_project_id = ? AND status = 'go' AND undone_at IS NULL AND project_id IS NOT NULL ORDER BY id DESC LIMIT 1
`

// The copy of a project that went and wasn't undone, while its new project's there.
func (q *Queries) CopyWentTo(ctx context.Context, fromProjectID sql.NullInt64) (ProjectCopy, error) {
	row := q.db.QueryRowContext(ctx, copyWentTo, fromProjectID)
	var i ProjectCopy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromProjectID,
		&i.DeployID,
		&i.SnapshotRunID,
		&i.FromName,
		&i.ToName,
		&i.Sha,
		&i.RequestedBy,
		&i.Status,
		&i.Error,
		&i.Log,
		&i.HandedOver,
		&i.HandedOverAt,
		&i.UndoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deployCount = `-- name: DeployCount :one
SELECT count(*) FROM deploys WHERE project_id = ?
`

func (q *Queries) DeployCount(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, deployCount, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const lastGoBackup = `-- name: LastGoBackup :one
SELECT id, project_id, location_id, operation, kind, reason, status, deploy_number, scheduled_for, sha, snapshot_id, source_snapshot_id, bytes, found, error, log, token_digest, heartbeat_at, started_at, finished_at, created_at, updated_at FROM backup_runs WHERE project_id = ? AND operation = 'backup' AND status = 'go' ORDER BY id DESC LIMIT 1
`

func (q *Queries) LastGoBackup(ctx context.Context, projectID int64) (BackupRun, error) {
	row := q.db.QueryRowContext(ctx, lastGoBackup, projectID)
	var i BackupRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.LocationID,
		&i.Operation,
		&i.Kind,
		&i.Reason,
		&i.Status,
		&i.DeployNumber,
		&i.ScheduledFor,
		&i.Sha,
		&i.SnapshotID,
		&i.SourceSnapshotID,
		&i.Bytes,
		&i.Found,
		&i.Error,
		&i.Log,
		&i.TokenDigest,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestDeletion = `-- name: LatestDeletion :one
SELECT id, project_id, name, repo_url, requested_by, delete_backups, status, step, error, log, snapshot_id, snapshot_location_id, heartbeat_at, started_at, removing_at, finished_at, created_at, updated_at FROM project_deletions WHERE project_id = ? ORDER BY id DESC LIMIT 1
`

func (q *Queries) LatestDeletion(ctx context.Context, projectID sql.NullInt64) (ProjectDeletion, error) {
	row := q.db.QueryRowContext(ctx, latestDeletion, projectID)
	var i ProjectDeletion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.RepoUrl,
		&i.RequestedBy,
		&i.DeleteBackups,
		&i.Status,
		&i.Step,
		&i.Error,
		&i.Log,
		&i.SnapshotID,
		&i.SnapshotLocationID,
		&i.HeartbeatAt,
		&i.StartedAt,
		&i.RemovingAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const liveLocations = `-- name: LiveLocations :many
SELECT id, name, kind, settings, credentials, restic_password, is_default, acknowledged_at, verified_at, pruned_at, prune_error, created_at, updated_at FROM storage_locations WHERE acknowledged_at IS NOT NULL AND kind IN ('nfs', 'local') ORDER BY name
`

// Where a volume can live: set up, and a share or a folder.
func (q *Queries) LiveLocations(ctx context.Context) ([]StorageLocation, error) {
	rows, err := q.db.QueryContext(ctx, liveLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLocation{}
	for rows.Next() {
		var i StorageLocation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Settings,
			&i.Credentials,
			&i.ResticPassword,
			&i.IsDefault,
			&i.AcknowledgedAt,
			&i.VerifiedAt,
			&i.PrunedAt,
			&i.PruneError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readyLocations = `-- name: ReadyLocations :many
SELECT id, name, kind, settings, credentials, restic_password, is_default, acknowledged_at, verified_at, pruned_at, prune_error, created_at, updated_at FROM storage_locations WHERE acknowledged_at IS NOT NULL ORDER BY name
`

func (q *Queries) ReadyLocations(ctx context.Context) ([]StorageLocation, error) {
	rows, err := q.db.QueryContext(ctx, readyLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLocation{}
	for rows.Next() {
		var i StorageLocation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Settings,
			&i.Credentials,
			&i.ResticPassword,
			&i.IsDefault,
			&i.AcknowledgedAt,
			&i.VerifiedAt,
			&i.PrunedAt,
			&i.PruneError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentFailedCopyFrom = `-- name: RecentFailedCopyFrom :one
SELECT id, project_id, from_project_id, deploy_id, snapshot_run_id, from_name, to_name, sha, requested_by, status, error, log, handed_over, handed_over_at, undone_at, created_at, updated_at FROM project_copies c WHERE c.from_project_id = ?1 AND c.status = 'no_go' AND c.updated_at >= ?2
  AND NOT EXISTS (SELECT 1 FROM project_copies later WHERE later.from_project_id = ?1 AND later.status = 'go' AND later.id > c.id)
ORDER BY c.id DESC LIMIT 1
`

type RecentFailedCopyFromParams struct {
	ProjectID sql.NullInt64
	Since     time.Time
}

// A project's copy that failed since @since, unless a later one went.
func (q *Queries) RecentFailedCopyFrom(ctx context.Context, arg RecentFailedCopyFromParams) (ProjectCopy, error) {
	row := q.db.QueryRowContext(ctx, recentFailedCopyFrom, arg.ProjectID, arg.Since)
	var i ProjectCopy
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FromProjectID,
		&i.DeployID,
		&i.SnapshotRunID,
		&i.FromName,
		&i.ToName,
		&i.Sha,
		&i.RequestedBy,
		&i.Status,
		&i.Error,
		&i.Log,
		&i.HandedOver,
		&i.HandedOverAt,
		&i.UndoneAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const savedSecrets = `-- name: SavedSecrets :many
SELECT id, project_id, "key", value, created_at, updated_at FROM secrets WHERE project_id = ? ORDER BY key
`

func (q *Queries) SavedSecrets(ctx context.Context, projectID int64) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, savedSecrets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usedLocations = `-- name: UsedLocations :many
SELECT id, name, kind, settings, credentials, restic_password, is_default, acknowledged_at, verified_at, pruned_at, prune_error, created_at, updated_at FROM storage_locations WHERE acknowledged_at IS NOT NULL
  AND (id IN (SELECT runs.location_id FROM backup_runs runs WHERE runs.project_id = ?1 AND runs.operation = 'backup')
    OR id IN (SELECT gone.snapshot_location_id FROM project_deletions gone WHERE gone.name = ?2 AND gone.snapshot_location_id IS NOT NULL))
ORDER BY name
`

type UsedLocationsParams struct {
	Project int64
	Name    string
}

// Where a project's backups are: the locations it backed up to, and where
// a deleted project of its name left its final snapshot.
func (q *Queries) UsedLocations(ctx context.Context, arg UsedLocationsParams) ([]StorageLocation, error) {
	rows, err := q.db.QueryContext(ctx, usedLocations, arg.Project, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StorageLocation{}
	for rows.Next() {
		var i StorageLocation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Settings,
			&i.Credentials,
			&i.ResticPassword,
			&i.IsDefault,
			&i.AcknowledgedAt,
			&i.VerifiedAt,
			&i.PrunedAt,
			&i.PruneError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
