// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package models

import (
	"context"
	"database/sql"
	"time"

	"github.com/scttymn/gantry/crypt"
)

const acknowledgeLocation = `-- name: AcknowledgeLocation :exec
UPDATE storage_locations SET acknowledged_at = ?1, updated_at = ?1 WHERE id = ?2
`

type AcknowledgeLocationParams struct {
	Now sql.NullTime
	ID  int64
}

func (q *Queries) AcknowledgeLocation(ctx context.Context, arg AcknowledgeLocationParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeLocation, arg.Now, arg.ID)
	return err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO storage_locations (name, kind, settings, credentials, restic_password) VALUES (?, ?, ?, ?, ?) RETURNING id, name, kind, settings, credentials, restic_password, is_default, acknowledged_at, verified_at, pruned_at, prune_error, created_at, updated_at
`

type CreateLocationParams struct {
	Name           string
	Kind           string
	Settings       Settings
	Credentials    crypt.String
	ResticPassword crypt.String
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.Name,
		arg.Kind,
		arg.Settings,
		arg.Credentials,
		arg.ResticPassword,
	)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Settings,
		&i.Credentials,
		&i.ResticPassword,
		&i.IsDefault,
		&i.AcknowledgedAt,
		&i.VerifiedAt,
		&i.PrunedAt,
		&i.PruneError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishStorageSetup = `-- name: FinishStorageSetup :exec
UPDATE storage_locations SET is_default = (id = ?1),
  acknowledged_at = CASE WHEN id = ?1 THEN ?2 ELSE acknowledged_at END,
  updated_at = CASE WHEN id = ?1 THEN ?2 ELSE updated_at END
`

type FinishStorageSetupParams struct {
	ID  int64
	Now sql.NullTime
}

// Its password saved: the location confirmed, and the default.
func (q *Queries) FinishStorageSetup(ctx context.Context, arg FinishStorageSetupParams) error {
	_, err := q.db.ExecContext(ctx, finishStorageSetup, arg.ID, arg.Now)
	return err
}

const recentUpdates = `-- name: RecentUpdates :many
SELECT id, to_version, from_version, status, step, log, started_at, finished_at, created_at, updated_at FROM server_updates ORDER BY id DESC LIMIT 10
`

func (q *Queries) RecentUpdates(ctx context.Context) ([]ServerUpdate, error) {
	rows, err := q.db.QueryContext(ctx, recentUpdates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServerUpdate{}
	for rows.Next() {
		var i ServerUpdate
		if err := rows.Scan(
			&i.ID,
			&i.ToVersion,
			&i.FromVersion,
			&i.Status,
			&i.Step,
			&i.Log,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetLocation = `-- name: ResetLocation :one
UPDATE storage_locations SET kind = ?, settings = ?, credentials = ?, updated_at = ? WHERE id = ? RETURNING id, name, kind, settings, credentials, restic_password, is_default, acknowledged_at, verified_at, pruned_at, prune_error, created_at, updated_at
`

type ResetLocationParams struct {
	Kind        string
	Settings    Settings
	Credentials crypt.String
	UpdatedAt   time.Time
	ID          int64
}

// A location set up again before it was confirmed: its password stays, so
// what an earlier try created can still be opened.
func (q *Queries) ResetLocation(ctx context.Context, arg ResetLocationParams) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, resetLocation,
		arg.Kind,
		arg.Settings,
		arg.Credentials,
		arg.UpdatedAt,
		arg.ID,
	)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Settings,
		&i.Credentials,
		&i.ResticPassword,
		&i.IsDefault,
		&i.AcknowledgedAt,
		&i.VerifiedAt,
		&i.PrunedAt,
		&i.PruneError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setLocationVerified = `-- name: SetLocationVerified :exec
UPDATE storage_locations SET verified_at = ?1, updated_at = ?1 WHERE id = ?2
`

type SetLocationVerifiedParams struct {
	Now sql.NullTime
	ID  int64
}

func (q *Queries) SetLocationVerified(ctx context.Context, arg SetLocationVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, setLocationVerified, arg.Now, arg.ID)
	return err
}

const setupCandidate = `-- name: SetupCandidate :one
SELECT id, name, kind, settings, credentials, restic_password, is_default, acknowledged_at, verified_at, pruned_at, prune_error, created_at, updated_at FROM storage_locations WHERE acknowledged_at IS NULL AND verified_at IS NOT NULL ORDER BY id DESC LIMIT 1
`

// The location setup's storage step made: tested, its password not yet
// confirmed saved.
func (q *Queries) SetupCandidate(ctx context.Context) (StorageLocation, error) {
	row := q.db.QueryRowContext(ctx, setupCandidate)
	var i StorageLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Settings,
		&i.Credentials,
		&i.ResticPassword,
		&i.IsDefault,
		&i.AcknowledgedAt,
		&i.VerifiedAt,
		&i.PrunedAt,
		&i.PruneError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateByID = `-- name: UpdateByID :one
SELECT id, to_version, from_version, status, step, log, started_at, finished_at, created_at, updated_at FROM server_updates WHERE id = ?
`

func (q *Queries) UpdateByID(ctx context.Context, id int64) (ServerUpdate, error) {
	row := q.db.QueryRowContext(ctx, updateByID, id)
	var i ServerUpdate
	err := row.Scan(
		&i.ID,
		&i.ToVersion,
		&i.FromVersion,
		&i.Status,
		&i.Step,
		&i.Log,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
