// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package models

import (
	"context"
	"time"
)

const defaultStorageReady = `-- name: DefaultStorageReady :one
SELECT EXISTS (SELECT 1 FROM storage_locations WHERE is_default AND acknowledged_at IS NOT NULL) AS ready
`

func (q *Queries) DefaultStorageReady(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, defaultStorageReady)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}

const liveRunners = `-- name: LiveRunners :one
SELECT count(*) FROM runners WHERE last_seen_at >= ?
`

// Runners heard from in the last minute.
func (q *Queries) LiveRunners(ctx context.Context, lastSeenAt time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, liveRunners, lastSeenAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (SELECT 1 FROM users) AS present
`

func (q *Queries) UserExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists)
	var present bool
	err := row.Scan(&present)
	return present, err
}
