#!/bin/sh
# Houston server installer. Run as root on Ubuntu LTS or Debian stable:
#
#   curl -fsSL <install-url>/install.sh | sudo sh
#
# Until Mission Control's image is published, it's built from a Houston
# checkout on the server: HOUSTON_SOURCE=/path/to/houston sh install.sh
#
# Rerunning repairs and updates. Generated secrets are kept.
set -eu

HOUSTON_DIR="${HOUSTON_DIR:-/opt/houston}"
HOUSTON_SOURCE="${HOUSTON_SOURCE:-}"
IMAGE="houston/mission-control:local"
CLOUDFLARED_IMAGE="cloudflare/cloudflared:2026.9.1"
KAMAL_IMAGE="ghcr.io/basecamp/kamal:v2.12.0"
REGISTRY_IMAGE="registry:3"

say() { printf '%s\n' "$*"; }
compose() { docker compose -f "$HOUSTON_DIR/compose.yml" "$@"; }
step() { printf '==> %s\n' "$*"; }
fail() { printf 'houston install: %s\n' "$*" >&2; exit 1; }

check_system() {
  [ "$(id -u)" = 0 ] || fail "run it as root (for example: sudo sh install.sh)"
  [ -r /etc/os-release ] || fail "can't read /etc/os-release; Houston supports Ubuntu LTS and Debian stable"
  # shellcheck disable=SC1091
  . /etc/os-release
  case "${ID:-}" in
    ubuntu | debian) ;;
    *) fail "Houston supports Ubuntu LTS and Debian stable; this is ${PRETTY_NAME:-an unknown system}" ;;
  esac
  [ -n "$HOUSTON_SOURCE" ] || fail "set HOUSTON_SOURCE to a Houston checkout (published images come later)"
  [ -f "$HOUSTON_SOURCE/mission_control/Dockerfile" ] || fail "HOUSTON_SOURCE=$HOUSTON_SOURCE has no mission_control/Dockerfile"
}

install_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    step "Docker is installed"
  else
    step "Installing Docker"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl >/dev/null
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL "https://download.docker.com/linux/$ID/gpg" -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
    printf 'deb [arch=%s signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/%s %s stable\n' \
      "$(dpkg --print-architecture)" "$ID" "$VERSION_CODENAME" >/etc/apt/sources.list.d/docker.list
    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null
  fi
  systemctl enable --now docker >/dev/null 2>&1 || true
  if ! command -v git >/dev/null 2>&1; then
    step "Installing git (houston deploy reads the checkout)"
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git >/dev/null
  fi
  if ! command -v sshd >/dev/null 2>&1 && [ ! -x /usr/sbin/sshd ]; then
    step "Installing OpenSSH server (Kamal deploys to this host over SSH)"
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq openssh-server >/dev/null
  fi
}

create_user() {
  if ! id houston >/dev/null 2>&1; then
    step "Creating the houston user"
    useradd --create-home --shell /bin/bash houston
  fi
  usermod -aG docker houston
  home=$(getent passwd houston | cut -d: -f6)
  install -d -m 700 -o houston -g houston "$home/.ssh"
  if [ ! -f "$home/.ssh/id_ed25519" ]; then
    su houston -c "ssh-keygen -q -t ed25519 -N '' -C houston@$(hostname) -f '$home/.ssh/id_ed25519'"
  fi
  touch "$home/.ssh/authorized_keys"
  if ! grep -qF "$(cat "$home/.ssh/id_ed25519.pub")" "$home/.ssh/authorized_keys"; then
    cat "$home/.ssh/id_ed25519.pub" >>"$home/.ssh/authorized_keys"
  fi
  chown houston:houston "$home/.ssh/authorized_keys"
  chmod 600 "$home/.ssh/authorized_keys"
}

random() { head -c 48 /dev/urandom | base64 | tr -d '\n/+='; }

write_env() {
  install -d -m 755 "$HOUSTON_DIR"
  if [ -f "$HOUSTON_DIR/.env" ]; then
    step "Keeping the existing secrets in $HOUSTON_DIR/.env"
  else
    step "Generating secrets in $HOUSTON_DIR/.env"
    umask 077
    {
      say "# Generated by the Houston installer. Losing these locks away every encrypted secret."
      say "SECRET_KEY_BASE=$(random)$(random)"
      say "AR_ENCRYPTION_PRIMARY_KEY=$(random)"
      say "AR_ENCRYPTION_DETERMINISTIC_KEY=$(random)"
      say "AR_ENCRYPTION_KEY_DERIVATION_SALT=$(random)"
    } >"$HOUSTON_DIR/.env"
    umask 022
  fi
  # Installs from before build step 3 have no runner token yet.
  if ! grep -q '^HOUSTON_RUNNER_TOKEN=' "$HOUSTON_DIR/.env"; then
    say "HOUSTON_RUNNER_TOKEN=$(random)" >>"$HOUSTON_DIR/.env"
  fi
  chmod 600 "$HOUSTON_DIR/.env"
}

# houston deploy, run as the houston user, reads the runner token from here.
write_runner_token() {
  home=$(getent passwd houston | cut -d: -f6)
  install -d -m 700 -o houston -g houston "$home/.config" "$home/.config/houston"
  umask 077
  sed -n 's/^HOUSTON_RUNNER_TOKEN=//p' "$HOUSTON_DIR/.env" >"$home/.config/houston/runner-token"
  umask 022
  chown houston:houston "$home/.config/houston/runner-token"
  chmod 600 "$home/.config/houston/runner-token"
}

# The houston CLI, built from the checkout until binaries are published.
install_cli() {
  step "Building the houston CLI from $HOUSTON_SOURCE"
  case "$(uname -m)" in
    x86_64) arch=amd64 ;;
    aarch64 | arm64) arch=arm64 ;;
    *) fail "unsupported architecture: $(uname -m)" ;;
  esac
  out=$(mktemp -d)
  docker build --quiet --target release --output "type=local,dest=$out" "$HOUSTON_SOURCE" >/dev/null
  install -m 755 "$out/houston-linux-$arch" /usr/local/bin/houston
  ln -sf houston /usr/local/bin/hou
  rm -rf "$out"
  docker pull --quiet "$KAMAL_IMAGE" >/dev/null
}

write_compose() {
  docker_gid=$(getent group docker | cut -d: -f3)
  step "Writing $HOUSTON_DIR/compose.yml"
  cat >"$HOUSTON_DIR/compose.yml" <<EOF
# Written by the Houston installer; rerunning it rewrites this file.
name: houston

services:
  mission-control:
    image: $IMAGE
    restart: unless-stopped
    env_file: .env
    environment:
      RAILS_ENV: production
      SOLID_QUEUE_IN_PUMA: "1"
      HOUSTON_TUNNEL_TOKEN_PATH: /houston/tunnel-token
    ports:
      - "3000:80"
    group_add:
      - "$docker_gid"
    volumes:
      - mission-control-storage:/rails/storage
      - houston-config:/houston
      - /var/run/docker.sock:/var/run/docker.sock

  # Waits for the token Mission Control writes in setup step 2, then connects.
  cloudflared:
    image: $CLOUDFLARED_IMAGE
    restart: unless-stopped
    user: "1000:1000"
    command: ["tunnel", "--no-autoupdate", "run", "--token-file", "/houston/tunnel-token"]
    volumes:
      - houston-config:/houston:ro
    networks:
      - default
      - kamal

  registry:
    image: $REGISTRY_IMAGE
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - registry-data:/var/lib/registry

volumes:
  mission-control-storage:
  houston-config:
  registry-data:

networks:
  kamal:
    external: true
EOF
}

start() {
  docker network inspect kamal >/dev/null 2>&1 || docker network create kamal >/dev/null
  step "Building Mission Control from $HOUSTON_SOURCE"
  docker build --quiet --target production -t "$IMAGE" "$HOUSTON_SOURCE/mission_control" >/dev/null
  compose create --quiet-pull >/dev/null 2>&1 || compose create
  # Mission Control (uid 1000) writes the tunnel token for cloudflared here.
  docker run --rm --user root --entrypoint chown -v houston_houston-config:/houston "$IMAGE" 1000:1000 /houston
  step "Starting Houston"
  compose up -d --remove-orphans >/dev/null 2>&1 || compose up -d --remove-orphans

  tries=0
  until curl -fs -o /dev/null http://127.0.0.1:3000/up; do
    tries=$((tries + 1))
    [ "$tries" -lt 90 ] || fail "Mission Control didn't come up; see: docker compose -f $HOUSTON_DIR/compose.yml logs mission-control"
    sleep 2
  done
}

report() {
  lan_ip=$(hostname -I 2>/dev/null | awk '{print $1}')
  url="http://${lan_ip:-<this server>}:3000"
  if code=$(compose exec -T mission-control bin/rails houston:setup_code 2>/dev/null); then
    say ""
    say "Houston is running."
    say "Finish setup at  $url"
    say "Setup code       $code"
  else
    say ""
    say "Houston is running. Setup is already complete; sign in at $url (or admin.<your base domain>)."
  fi
}

check_system
install_docker
create_user
write_env
write_runner_token
write_compose
install_cli
start
report
